### ISSUE TITLE
Need to add [Gimbal start] to work

### ISSUE THREAD

**Issue by fdellutri** [happydenn/cordova-plugin-gimbal2#4]
Hi,
my IOS application was unable to find any Gimbal beacons until I patched the Gimbal.m as following:

``` objective-c
- (void)initialize:(CDVInvokedUrlCommand *)command {
    NSString *apiKey = command.arguments[0];
    statusCallbackId = command.callbackId;

    // Patch starts here
    [Gimbal start];
    // Patch ends here

    [Gimbal setAPIKey:apiKey options:nil];
}
```

**Comment by happydenn** [comment]
Nice find! Actually I think Gimbal must have updated their API since I don't recall this start method from earlier SDK versions.

Anyway, thanks! It would be nice if you could send a pull request and I'll happily merge it :)
